### ISSUE TITLE
Implement OAuth 

### ISSUE THREAD

**Issue by glasnt** [LABHR/js-hatrack#5]
Instead of using a form input, it'd be safer and easier in the long run to use OAuth

See @edunham's comment over in https://github.com/LABHR/octohatrack/issues/34#issuecomment-178960698

GitHub's doco on this shouldn't be too hard to go through: https://developer.github.com/v3/oauth/

I've not actually done this before, but it shouldn't be too hard.

**Comment by leesdolphin** [comment]
So my understanding of the OAuth flow is:
 1. We redirect to GitHub using our client ID
 2. Then after the user logs in and authorises our application, GitHub redirects back to our site
 3. Then we send a post request to GitHub with our client ID, client secret and a code that GitHub sent us. This then responds with our access token.
 4. Profit, or build _all_ the hat racks

My concern is that, without a server, we are going to have to store the client secret in the JavaScript which is against the recommendations in the [documentation](https://developer.github.com/v3/oauth/#markdown-toc)(2nd paragraph).

**Comment by glasnt** [comment]
I can get a server happening if required. I are sys admin :D

**Comment by glasnt** [comment]
Can you point to the specific para where it says you shouldn't have oauth on a gh-pages site? I can't see a specific reference (or i'm still half asleep)

Serverless oauth is possible http://oauth-io.github.io/oauth-js/ and we're only using public access tokens, which only allow read, and aren't auto-removed if they are committed into repos (see previous discussions in octohatrack https://github.com/LABHR/octohatrack/issues/30)

**Comment by leesdolphin** [comment]
To quote the 2nd paragraph on the [OAuth page](https://developer.github.com/v3/oauth/#markdown-toc)(emphasis mine):

> All developers need to register their application before getting started. A registered OAuth application is assigned a unique Client ID and Client Secret. **The Client Secret should not be shared.** You may create a personal access token for your own use or implement the web flow below to allow other users to authorize your application.

-------------

A service like oauth-io looks good for now, My concern is *if* or *when* we reach the limits of the free plan; how will we manage. I guess we will jump that bridge when we get to it.

A project I found whilst looking into this was [benbalter/jekyll-auth](https://github.com/benbalter/jekyll-auth) which deploys a small ruby application to Heroku to perform the OAuth login. Effectively doing what oauth-io does except on a Heroku box instead of 'as a service'.

**Comment by glasnt** [comment]
Resolved in #8
